name: Release
on:
  release:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build wheel for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-22.04"
          - "macos-14"
    steps:
      - uses: pypa/cibuildwheel@v2.16.5
      - uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.os }}
          path: ./wheelhouse/*.whl
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
            python -m pip install -U pip
            python -m pip install -U build twine
      - name: Build sdist
        run: |
          python -m pip install -U pip
          python -m build --sdist .
      - uses: actions/upload-artifact@v4
        with:
          path: dist/*.tar.gz

  publish:
    environment:
      name: pypi
      url: https://pypi.org/p/fsps
    permissions:
      id-token: write
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@v1.8.12
